---
- name: configure local dns 
  shell: >
    nmcli con mod "{{ ansible_default_ipv4.interface }}" ipv4.dns "{{ hostvars[item]['ansible_default_ipv4']['address'] }}" &&
    nmcli con reload &&
    nmcli con up "{{ ansible_default_ipv4.interface }}"
  loop: "{{ groups['zimbra_ldap'] }}"

- name: configure firewall ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 25/tcp
    - 465/tcp
    - 587/tcp

- name: download zimbra installer
  get_url:
    url: https://files.zimbra.com/downloads/8.8.15_GA/zcs-8.8.15_GA_3953.RHEL8_64.20200629025823.tgz
    dest: /root
    checksum: sha256:https://files.zimbra.com/downloads/8.8.15_GA/zcs-8.8.15_GA_3953.RHEL8_64.20200629025823.tgz.sha256

- name: extract zimbra installer
  unarchive:
    remote_src: yes
    src: /root/zcs-8.8.15_GA_3953.RHEL8_64.20200629025823.tgz
    dest: /root

- name: configure answer file
  template:
    src: mta_answers.j2
    dest: /tmp/mta_answers.txt

- name: capture mailboxd memory
  shell: free -m | awk 'NR==2{printf "%.0f\n", $2*0.25 }'
  register: zimbra_mailboxd_memory

- name: capture system memory
  shell: free -h | awk 'NR==2{printf "%.0f\n", $2 }'
  register: zimbra_system_memory

- name: configure config file
  template:
    src: mta_config.j2
    dest: /tmp/mta_config.txt

- name: run zimbra installer phase 1
  shell: ./install.sh -s < /tmp/mta_answers.txt
  args:
    chdir: /root/zcs-8.8.15_GA_3953.RHEL8_64.20200629025823

- name: run zimbra installer phase 2
  shell: /opt/zimbra/libexec/zmsetup.pl -c /tmp/mta_config.txt
