---
  - name: configure local dns
    shell: >
      nmcli con mod "{{ zimbra_network_name }}" ipv4.dns "{{ zimbra_ldap_ip }}" &&
      nmcli con reload &&
      nmcli con up "{{ zimbra_network_name }}"

  - name: configure chronyd
    service:
      name: chronyd
      state: started
      enabled: yes

  - name: configure time zone
    timezone:
      name: "{{ zimbra_timezone }}"

  - name: configure time sync
    shell: timedatectl set-ntp true

  - name: restart chronyd
    service:
      name: chronyd
      state: restarted

  - name: configure hostname
    hostname:
      name: "{{ zimbra_mta_fqdn }}"

  - name: configure hosts file
    lineinfile:
      line: "{{ zimbra_mta_ip }} {{ zimbra_mta_fqdn }} {{ zimbra_mta_shortname }}"
      path: '/etc/hosts'

  - name: install utilities
    yum:
      name:
        - bash-completion
        - tmux
        - telnet
        - bind-utils
        - tcpdump
        - wget
        - lsof
        - rsync
        - tar
        - nmap-ncat
      state: present

  - name: perform update
    yum:
      name: '*'
      state: latest

  - name: configure firewall ports
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: yes
    loop:
      - 25/tcp
      - 465/tcp
      - 587/tcp

  - name: configure firewall rich rule
    firewalld:
      rich_rule: rule family="ipv4" source address="192.168.122.0/24" accept
      permanent: yes
      state: enabled
      immediate: yes

  - name: check postfix rpm
    shell: rpm -q postfix
    register: postfix_rpm
    ignore_errors: yes

  - name: disable postfix
    service:
      name: postfix
      state: stopped
      enabled: no
    when: postfix_rpm.rc == 0

  - name: install dependencies
    yum:
      name:
        - perl
        - net-tools
      state: present

  - name: download zimbra installer
    get_url:
      url: https://files.zimbra.com/downloads/8.8.15_GA/zcs-8.8.15_GA_3953.RHEL8_64.20200629025823.tgz
      dest: /tmp
      checksum: sha256:https://files.zimbra.com/downloads/8.8.15_GA/zcs-8.8.15_GA_3953.RHEL8_64.20200629025823.tgz.sha256

  - name: extract zimbra installer
    unarchive:
      remote_src: yes
      src: /tmp/zcs-8.8.15_GA_3953.RHEL8_64.20200629025823.tgz
      dest: /tmp

  - name: configure answer file
    template:
      src: mta_answers.j2
      dest: /tmp/mta_answers.txt

  - name: configure config file
    template:
      src: mta_config.j2
      dest: /tmp/mta_config.txt

  - name: run zimbra installer phase 1
    shell: ./install.sh -s < /tmp/mta_answers.txt
    args:
      chdir: /tmp/zcs-8.8.15_GA_3953.RHEL8_64.20200629025823

  - name: run zimbra installer phase 2
    shell: /opt/zimbra/libexec/zmsetup.pl -c /tmp/mta_config.txt
